
package com.krawczyk.lifesum;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table FOOD.
 */
public class Food {
    @SerializedName("id")
    private Long id;

    @SerializedName("categoryid")
    private Integer categoryid;

    @SerializedName("fiber")
    private Float fiber;

    @SerializedName("headimage")
    private String headimage;

    @SerializedName("pcsingram")
    private String pcsingram;

    @SerializedName("brand")
    private String brand;

    @SerializedName("unsaturatedfat")
    private Float unsaturatedfat;

    @SerializedName("fat")
    private Float fat;

    @SerializedName("servingcategory")
    private Integer servingcategory;

    @SerializedName("typeofmeasurement")
    private Integer typeofmeasurement;

    @SerializedName("protein")
    private Float protein;

    @SerializedName("defaultserving")
    private Integer defaultserving;

    @SerializedName("mlingram")
    private Integer mlingram;

    @SerializedName("saturatedfat")
    private Float saturatedfat;

    @SerializedName("category")
    private String category;

    @SerializedName("verified")
    private Boolean verified;

    @SerializedName("title")
    private String title;

    @SerializedName("pcstext")
    private String pcstext;

    @SerializedName("sodium")
    private Float sodium;

    @SerializedName("carbohydrates")
    private Float carbohydrates;

    @SerializedName("showonlysametype")
    private Integer showonlysametype;

    @SerializedName("calories")
    private Integer calories;

    @SerializedName("serving_version")
    private Integer serving_version;

    @SerializedName("sugar")
    private Float sugar;

    @SerializedName("measurementid")
    private Integer measurementid;

    @SerializedName("cholesterol")
    private Float cholesterol;

    @SerializedName("gramsperserving")
    private Float gramsperserving;

    @SerializedName("showmeasurement")
    private Integer showmeasurement;

    @SerializedName("potassium")
    private Float potassium;

    public Food() {
    }

    public Food(Long id, Integer categoryid, Float fiber, String headimage, String pcsingram, String brand, Float unsaturatedfat, Float fat,
            Integer servingcategory, Integer typeofmeasurement, Float protein, Integer defaultserving, Integer mlingram, Float saturatedfat,
            String category, Boolean verified, String title, String pcstext, Float sodium, Float carbohydrates, Integer showonlysametype,
            Integer calories, Integer serving_version, Float sugar, Integer measurementid, Float cholesterol, Float gramsperserving,
            Integer showmeasurement, Float potassium) {
        this.id = id;
        this.categoryid = categoryid;
        this.fiber = fiber;
        this.headimage = headimage;
        this.pcsingram = pcsingram;
        this.brand = brand;
        this.unsaturatedfat = unsaturatedfat;
        this.fat = fat;
        this.servingcategory = servingcategory;
        this.typeofmeasurement = typeofmeasurement;
        this.protein = protein;
        this.defaultserving = defaultserving;
        this.mlingram = mlingram;
        this.saturatedfat = saturatedfat;
        this.category = category;
        this.verified = verified;
        this.title = title;
        this.pcstext = pcstext;
        this.sodium = sodium;
        this.carbohydrates = carbohydrates;
        this.showonlysametype = showonlysametype;
        this.calories = calories;
        this.serving_version = serving_version;
        this.sugar = sugar;
        this.measurementid = measurementid;
        this.cholesterol = cholesterol;
        this.gramsperserving = gramsperserving;
        this.showmeasurement = showmeasurement;
        this.potassium = potassium;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCategoryid() {
        return categoryid;
    }

    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    public Float getFiber() {
        return fiber;
    }

    public void setFiber(Float fiber) {
        this.fiber = fiber;
    }

    public String getHeadimage() {
        return headimage;
    }

    public void setHeadimage(String headimage) {
        this.headimage = headimage;
    }

    public String getPcsingram() {
        return pcsingram;
    }

    public void setPcsingram(String pcsingram) {
        this.pcsingram = pcsingram;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Float getUnsaturatedfat() {
        return unsaturatedfat;
    }

    public void setUnsaturatedfat(Float unsaturatedfat) {
        this.unsaturatedfat = unsaturatedfat;
    }

    public Float getFat() {
        return fat;
    }

    public void setFat(Float fat) {
        this.fat = fat;
    }

    public Integer getServingcategory() {
        return servingcategory;
    }

    public void setServingcategory(Integer servingcategory) {
        this.servingcategory = servingcategory;
    }

    public Integer getTypeofmeasurement() {
        return typeofmeasurement;
    }

    public void setTypeofmeasurement(Integer typeofmeasurement) {
        this.typeofmeasurement = typeofmeasurement;
    }

    public Float getProtein() {
        return protein;
    }

    public void setProtein(Float protein) {
        this.protein = protein;
    }

    public Integer getDefaultserving() {
        return defaultserving;
    }

    public void setDefaultserving(Integer defaultserving) {
        this.defaultserving = defaultserving;
    }

    public Integer getMlingram() {
        return mlingram;
    }

    public void setMlingram(Integer mlingram) {
        this.mlingram = mlingram;
    }

    public Float getSaturatedfat() {
        return saturatedfat;
    }

    public void setSaturatedfat(Float saturatedfat) {
        this.saturatedfat = saturatedfat;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPcstext() {
        return pcstext;
    }

    public void setPcstext(String pcstext) {
        this.pcstext = pcstext;
    }

    public Float getSodium() {
        return sodium;
    }

    public void setSodium(Float sodium) {
        this.sodium = sodium;
    }

    public Float getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(Float carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public Integer getShowonlysametype() {
        return showonlysametype;
    }

    public void setShowonlysametype(Integer showonlysametype) {
        this.showonlysametype = showonlysametype;
    }

    public Integer getCalories() {
        return calories;
    }

    public void setCalories(Integer calories) {
        this.calories = calories;
    }

    public Integer getServing_version() {
        return serving_version;
    }

    public void setServing_version(Integer serving_version) {
        this.serving_version = serving_version;
    }

    public Float getSugar() {
        return sugar;
    }

    public void setSugar(Float sugar) {
        this.sugar = sugar;
    }

    public Integer getMeasurementid() {
        return measurementid;
    }

    public void setMeasurementid(Integer measurementid) {
        this.measurementid = measurementid;
    }

    public Float getCholesterol() {
        return cholesterol;
    }

    public void setCholesterol(Float cholesterol) {
        this.cholesterol = cholesterol;
    }

    public Float getGramsperserving() {
        return gramsperserving;
    }

    public void setGramsperserving(Float gramsperserving) {
        this.gramsperserving = gramsperserving;
    }

    public Integer getShowmeasurement() {
        return showmeasurement;
    }

    public void setShowmeasurement(Integer showmeasurement) {
        this.showmeasurement = showmeasurement;
    }

    public Float getPotassium() {
        return potassium;
    }

    public void setPotassium(Float potassium) {
        this.potassium = potassium;
    }

}
